server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://210.211.125.205:3306/kbvaamfl_mymusic_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: kbvaamfl_TrungHieu
    password: Doanhieu@1
  jpa:
    hibernate:
      ddl-auto: none  # tắt auto update schema để khởi động nhanh hơn
    show-sql: false   # tắt log query khi deploy cho đỡ nặng
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false  # tăng tốc start-up, bỏ metadata check

logging:
  level:
    root: INFO
